# ─── VERSION IDENTITY ───────────────────────────────────────────────────
#
# Electrin tracks two independent version numbers:
#
#   ELECTRIN_VERSION - Electrin's own release identity. This is what users,
#     packaging (APK/AppImage/installer naming), the About dialog, the
#     --version CLI output, crash reports, and the update checker all deal
#     with. Bump this on every Electrin release.
#
#   ELECTRUM_VERSION - the nearest upstream Electrum release actually merged
#     into this fork. Kept purely for internal/protocol purposes: plugin
#     min/max version gating (electrum/plugin.py, via distutils.StrictVersion
#     — must stay in strict X.Y.Z[.N] form) and the Electrum-protocol P2P
#     user-agent string sent to Fulcrum-rin servers. Bump this only when
#     re-syncing with upstream, not on every Electrin release.
#
# Do not conflate the two: call sites that are user-facing (About dialog,
# CLI --version, crash reports, update checker, packaging) should read
# ELECTRIN_VERSION; call sites that are upstream-protocol/plugin-compat
# machinery should keep reading ELECTRUM_VERSION.
# ─────────────────────────────────────────────────────────────────────────

ELECTRIN_VERSION = '1.0.0-beta.1'   # Electrin's own release identity
ELECTRUM_VERSION = '4.7.2'          # nearest upstream Electrum release merged (internal/protocol use only)

PROTOCOL_VERSION_MIN = '1.4'     # electrum protocol
PROTOCOL_VERSION_MAX = '1.6'

# ─── SEED VERSION PREFIXES ──────────────────────────────────────────────
#
# WARNING — CROSS-CHAIN SEED COLLISION RISK
#
# Electrin currently uses the SAME seed prefixes as upstream Electrum.
# This means a mnemonic generated by Electrin is also valid in Electrum
# (and vice versa), so the SAME 12-word phrase could unlock:
#
#   • a Rincoin wallet in Electrin, AND
#   • a Bitcoin wallet in Electrum.
#
# This is by design in the upstream Electrum model (the seed encodes
# wallet *type* — standard / segwit / 2FA — but not the *chain*).
# The chain is determined by the software and the derivation path:
#
#   Electrum Bitcoin:  m/44'/0'/...   or m/84'/0'/...
#   Electrin Rincoin:  m/44'/9555'/... or m/84'/9555'/...  (BIP44_COIN_TYPE)
#
# IMPACT:
#   • A user who restores the same mnemonic in both Electrum and Electrin
#     will get different addresses on different chains — no fund collision.
#   • However, it is *confusing*: user might think the seed "belongs" to
#     one chain when it actually works on both.
#   • If Rincoin ever needed custom seed semantics (e.g. embedded chain ID,
#     or post-quantum signature flags), the shared prefixes would conflict.
#
# HOW TO FIX (optional, non-urgent):
#   1. Choose new unique prefixes, e.g. SEED_PREFIX = '0a' (must not
#      collide with upstream '01', '100', '101', '102').
#   2. Update `make_seed()` and `calc_seed_type()` in mnemonic.py.
#   3. Add a migration path: on wallet open, detect old-prefix seeds
#      and either accept them silently or prompt the user to re-derive.
#   4. The PBKDF2 salt in `mnemonic_to_seed()` is `b'electrum'` — changing
#      it to `b'electrin'` would make the same mnemonic produce a DIFFERENT
#      master key on Electrin vs Electrum.  This is the *most powerful*
#      isolation mechanism but is a BREAKING CHANGE for existing wallets.
#   5. Changing the HMAC key in `is_new_seed()` from `b"Seed version"` to
#      e.g. `b"Electrin seed version"` would make ALL existing Electrin
#      mnemonics invalid — nuclear option, only for a completely fresh start.
#
# FULCRUM IMPACT: None.  Fulcrum-rin is a chain indexer that knows nothing
# about seeds or mnemonics.  Seed isolation is purely a client-side concern
# between Electrin and Electrum.  No Fulcrum changes are needed.
#
# RECOMMENDATION: Keep shared prefixes for now.  The BIP44 coin_type
# already provides sufficient chain isolation at the derivation level.
# Revisit only if Electrin needs chain-specific seed semantics.
#
# TODO [SEED-PREFIX]: Decide whether to adopt unique prefixes before
# Electrin reaches stable release.  Track in GitHub issue.
# ─────────────────────────────────────────────────────────────────────────

# The hash of the mnemonic seed must begin with this
SEED_PREFIX        = '01'      # Standard wallet
SEED_PREFIX_SW     = '100'     # Segwit wallet
SEED_PREFIX_2FA    = '101'     # Two-factor authentication
SEED_PREFIX_2FA_SW = '102'     # Two-factor auth, using segwit


def seed_prefix(seed_type):
    if seed_type == 'standard':
        return SEED_PREFIX
    elif seed_type == 'segwit':
        return SEED_PREFIX_SW
    elif seed_type == '2fa':
        return SEED_PREFIX_2FA
    elif seed_type == '2fa_segwit':
        return SEED_PREFIX_2FA_SW
    raise Exception(f"unknown seed_type: {seed_type!r}")
